initial action
cloudposse/github-action-datadog-notify pull request #2
Opened 2022-09-13 18:34 UTC by Benbentwo

## what
* Simple github action for notifying github of some event.

## why
* This could be to send pull request information or perhaps more usefully notify of deployment.

2022-09-13 18:43 UTC, osterman commented on README.yaml
> +            withDecryption: "true" # defaults to true
We should make this optional so that the action does not require AWS.

2022-09-13 18:44 UTC, osterman commented on README.yaml
> +            withDecryption: "true" # defaults to true
e.g. if the role is not set, look for datadog API key as a secret instead.

2022-09-13 18:44 UTC, osterman commented on action.yml
> +author: ben@cloudposse.com
lets change this maintainers@cloudposse.com

2022-09-13 18:50 UTC, Benbentwo commented on README.yaml
> +            withDecryption: "true" # defaults to true
so that's a full example of how to use, such as with our entire setup for SSM. The composite action itself only requires the `api_key` input be set.

2022-09-13 18:50 UTC, osterman commented on datadog-notify.sh
> +## Copied From https://raw.githubusercontent.com/dvmtn/datadog-notify/master/datadog-notify
Can we clone it at a specific SHA instead of copying it, to avoid copyright issues? There's no LICENSE and by adding it to our repo, we're applying our license which we do not have the copyright to do.

2022-09-13 18:55 UTC, Benbentwo commented on README.yaml
> +            withDecryption: "true" # defaults to true
I've added a minimal setup

2022-09-13 20:47 UTC, osterman commented on action.yml
> +        export DATADOG_API_KEY=${{ inputs.api_key }}
Super dangerous to do this, if the bash shell is changed to `bash -x` it will output the secret.

2022-09-13 20:49 UTC, osterman commented on action.yml
> +        export DATADOG_API_KEY=${{ inputs.api_key }}
use the `env` section of the step.

2022-09-13 20:49 UTC, osterman commented on action.yml
> +        export APPEND_HOSTNAME_TAG=${{ inputs.append_hostname_tag }}
Use env section of the step.

2022-09-13 20:53 UTC, osterman commented on datadog-notify.sh
> +response=$(curl -s -X POST -H "Content-type: application/json" -d "$(echo "${payload}" | sed ':a;N;$!ba;s/\n/ /g')" "$datadog")
https://docs.datadoghq.com/api/latest/authentication/?code-lang=curl
Use the datadog recommended way of passing the API key using a header. That way it does not appear in the logs.

2022-09-13 20:54 UTC, osterman commented on datadog-notify.sh
> +	tag="${APPEND_HOSTNAME_TAG}:$(hostname) $4"
inconsistent whitespace

2022-09-13 20:55 UTC, osterman commented on datadog-notify.sh
> +datadog="${api}/events?api_key=${api_key}"
Remove api_key from url

2022-09-13 20:57 UTC, osterman commented on datadog-notify.sh
> +##	Copyright (c) 2022 Developer Mountain and Adam Whittingham
```suggestion
##	Copyright (c) 2022 Developer Mountain and Adam Whittingham
##    Copyright (c) 2022 Cloud Posse, LLC <maintainers@cloudposse.com>
```

2022-09-13 21:01 UTC, osterman commented on datadog-notify.sh
> +## which is licensed MIT. This code is also licensed under the terms  of the MIT License.
```suggestion
## which is licensed MIT. This code is also licensed under the terms of the MIT License.
```

2022-09-14 22:22 UTC, osterman commented on datadog-notify.sh
> +## which is licensed MIT. This code is also licensed under the terms of the MIT License.
```suggestion
##  Copyright (c) 2022 Cloud Posse, LLC <maintainers@cloudposse.com>
##  The following code is a derivative work of the code from https://github.com/dvmtn/datadog-notify,
##  which is licensed MIT. This code is also licensed under the terms of the MIT License.
```

2022-09-21 19:37 UTC, srhopkins approved these changes
lgtm

2022-09-21 20:11 UTC, mcalhoun requested changes
A made a few small comments for consideration

2022-09-21 20:11 UTC, mcalhoun commented on README.md
> +  pull_request:
Shouldn't this still be restricted to PRs to `main`?

2022-09-21 20:11 UTC, mcalhoun commented on README.md
> +
nit: consider removing the blank line between keys with no values

2022-09-21 20:11 UTC, mcalhoun commented on README.md
> +jobs:
nit: consider adding a blank line between blocks

2022-09-21 20:11 UTC, mcalhoun commented on README.md
> +          # The part before equals is the ssm parameterName, and after is the ENV Variable name for the workflow.
Seems like this comment is extraneous

2022-09-21 20:11 UTC, mcalhoun commented on README.md
> +          withDecryption: "true" # defaults to true
nit: probably don't the comment (or the block if the comment is true ;) )

2022-09-22 14:31 UTC, mcalhoun approved these changes
LGTM!

2022-09-22 15:19 UTC, merged